// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlatformExampleApp.TextSnippet.Domain.ValueObjects;
using PlatformExampleApp.TextSnippet.Persistence.PostgreSql;

#nullable disable

namespace PlatformExampleApp.TextSnippet.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(TextSnippetDbContext))]
    partial class TextSnippetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Easy.Platform.Application.MessageBus.InboxPattern.PlatformInboxBusMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ConcurrencyUpdateToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConsumerBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastConsumeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastConsumeError")
                        .HasColumnType("text");

                    b.Property<string>("MessageTypeFullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("NextRetryProcessAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProduceFrom")
                        .HasColumnType("text");

                    b.Property<int?>("RetriedProcessCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RoutingKey");

                    b.HasIndex("ConsumeStatus", "LastConsumeDate");

                    b.HasIndex("LastConsumeDate", "ConsumeStatus");

                    b.HasIndex("ConsumeStatus", "NextRetryProcessAfter", "LastConsumeDate");

                    b.ToTable("PlatformInboxEventBusMessage", (string)null);
                });

            modelBuilder.Entity("Easy.Platform.Application.MessageBus.OutboxPattern.PlatformOutboxBusMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ConcurrencyUpdateToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSendError")
                        .HasColumnType("text");

                    b.Property<string>("MessageTypeFullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("NextRetryProcessAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RetriedProcessCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SendStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryProcessAfter");

                    b.HasIndex("RoutingKey");

                    b.HasIndex("LastSendDate", "SendStatus");

                    b.HasIndex("SendStatus", "LastSendDate");

                    b.HasIndex("SendStatus", "NextRetryProcessAfter", "LastSendDate");

                    b.ToTable("PlatformOutboxEventBusMessage", (string)null);
                });

            modelBuilder.Entity("Easy.Platform.Persistence.DataMigration.PlatformDataMigrationHistory", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("ApplicationDataMigrationHistoryDbSet");
                });

            modelBuilder.Entity("PlatformExampleApp.TextSnippet.Domain.Entities.TextSnippetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<ExampleAddressValueObject>("Address")
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("AddressStrings")
                        .HasColumnType("text[]");

                    b.Property<List<ExampleAddressValueObject>>("Addresses")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ConcurrencyUpdateToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SnippetText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Address"), "GIN");

                    b.HasIndex("AddressStrings");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AddressStrings"), "GIN");

                    b.HasIndex("Addresses");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Addresses"), "GIN");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("LastUpdatedBy");

                    b.HasIndex("LastUpdatedDate");

                    b.HasIndex("SnippetText")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SnippetText"), "GIN");

                    b.ToTable("TextSnippetEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
